### ISSUE TITLE
Having problems installing from a local layout

### ISSUE THREAD

**Issue by danhaywood** [jberezanski/ChocolateyPackages#121] opened 2021-11-06 08:42 UTC
HI Jakub,

first, thanks for the work you've put into these packages, they are well crafted and I'm keen to leverage them if I can.

What I'm trying to do is to use them in an enterprise "on-prem" context, to avoid pulling down the installation binaries from the internet (this is an enterprise context).  The solution I hit upon was to create a "layout" of all workloads as one big zip (17Gb for VS2017), and have created my own little choco package "VS2017InstallFiles" that basically downloads that zip from our own on-prem Nexus so that once this package is installed I have a layout on my C: drive under c:\programdata\chocolatey\lib\vs2017installfiles.  So far, so good.

What I am struggling with is how to then install VS2017 specifying the layout path.  Using your docs at https://github.com/jberezanski/ChocolateyPackages/blob/master/chocolatey-visualstudio.extension/EXAMPLES.md I have come up with:

cinst visualstudio2017enterprise --params "--bootstrapperPath c:\programdata\chocolatey\lib\vs2017installfiles\VS-2017-BT-15.7.0\vs_BuildTools.exe --noWeb"

However this fails with very little to go on (logs just say returned 1).  

Any clues how to debug this would be very much appreciated...?

**Comment by jberezanski** [comment] 2021-11-06 12:35
Hi Dan,

Your solution seems sound and the command line appears to be correct.

The VS Installer generates a lot of log files which usually quickly point to the cause of the problem. When installation is done by choco, these files end up in `$Env:TEMP\chocolatey` (and are named `dd_*.log`).

Apart from the log files, I'd check:
- whether VS installs successfully from your layout if you invoke it interactively (without choco) - this may detect some issues with the layout,
- whether VS installs successfully via choco without using your layout (pulling files from the internet) - this may detect some obstacles in the configuration of your workstations.

One disclaimer, though. It seems you are installing a very old VS 2017 version (15.7.0 was released in May 2018). There had been numerous changes to the VS installer behavior over the years, even breaking changes, to which I had to adapt the package scripts. I always intended to preserve backward compatibility, but I generally only test the packages with the latest versions of VS 2017, 2019 and 2022. So it should work, but then, it might not.

**Comment by danhaywood** [comment] 2021-11-11 06:18
Hi Jakub,

Many thanks for the quick reply and for these hints.  I haven't had the
chance yet to try out the debugging, but I'll post back here once I do.

On the topic of the old VS2017, actually I am working with the latest, I
just copied-n-pasted that snippet from a README doc in your repo.

Thanks again, will let you know.
Dan

**Comment by jberezanski** [comment] 2023-05-03 17:14
Closing due to inactivity.

**Closed by jberezanski** 2023-05-03 17:14 UTC
