### ISSUE TITLE
The install of visualstudio2017-workload-netcoretools was NOT successful

### ISSUE THREAD

**Issue by goffinf** [jberezanski/ChocolateyPackages#32] opened 2017-12-07 21:32 UTC
The following error is emitting when attempting to install this package on Windows Server 2016. Any chance you can take a look please :-

choco install visualstudio2017-workload-netcoretools --confirm --limit-output --timeout 21600 --package-parameters "--includeOptional"

ERROR: Exception calling "GetFullPath" with "1" argument(s): "The path is not of a legal form."
The install of visualstudio2017-workload-netcoretools was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\visua

**Comment by kilbypatrick** [comment] 2017-12-07 22:30
It seems several (all?) of the workload packages are affected by the same issue. I'm personally seeing it in the azure, netweb, node, netcoretools, and data packages. I assume the others are affected as well. @maaktweluit listed a possible fix in his bug report: https://github.com/jberezanski/ChocolateyPackages/issues/28

**Comment by jberezanski** [comment] 2017-12-08 17:37
Right, I'm closing it as duplicate of #28.

**Closed by jberezanski** 2017-12-08 17:37 UTC
