### ISSUE TITLE
netfx-4.7.2-devpack `string is missing the terminator: '`

### ISSUE THREAD

**Issue by BlythMeister** [jberezanski/ChocolateyPackages#118] opened 2021-09-30 09:51 UTC
When choco upgrade on netfx-4.7.2-devpack i get the following:

```
❯ choco upgrade netfx-4.7.2-devpack --verbose --overrideargs
Chocolatey v0.11.2
Upgrading the following packages:
netfx-4.7.2-devpack
By upgrading, you accept licenses for the packages.

You have netfx-4.7.2-devpack v4.7.2.20190225 installed. Version 4.7.2.20210903 is available based on your source(s).
[NuGet] Attempting to resolve dependency 'chocolatey-dotnetfx.extension (≥ 1.0.1)'.
Progress: Downloading netfx-4.7.2-devpack 4.7.2.20210903... 100%
[NuGet] Attempting to resolve dependency 'KB2919355 (≥ 1.0.20160915)'.
[NuGet] Attempting to resolve dependency 'KB2919442 (≥ 1.0.20160915)'.
[NuGet] Attempting to resolve dependency 'netfx-4.7.2 (≥ 4.7.2.0)'.
[NuGet] Uninstalling 'netfx-4.7.2-devpack 4.7.2.20190225'.
[NuGet] Successfully uninstalled 'netfx-4.7.2-devpack 4.7.2.20190225'.
[NuGet] Installing 'netfx-4.7.2-devpack 4.7.2.20210903'.
[NuGet] Successfully installed 'netfx-4.7.2-devpack 4.7.2.20210903'.

netfx-4.7.2-devpack v4.7.2.20210903 [Approved]
netfx-4.7.2-devpack package files upgrade completed. Performing other installation steps.
ERROR: The string is missing the terminator: '.
The upgrade of netfx-4.7.2-devpack was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\netfx-4.7.2-devpack\tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - netfx-4.7.2-devpack (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\netfx-4.7.2-devpack\tools\ChocolateyInstall.ps1'.
 See log for details.
 ```

Adding `--ignorerememberedargs` seems to fix this issue.
The remembered args appear to be from a visual studio install
`netfx-4.7.2-devpack - Adding remembered arguments for upgrade:  --package-parameters="'--quiet --norestart --wait --includeRecommended --includeOptional'" --cache-location="'C:\Users\chris.blyth\AppData\Local\Temp\chocolatey'"`

Full chocolatey log: [log.txt](https://github.com/jberezanski/ChocolateyPackages/files/7258597/log.txt)

**Comment by jberezanski** [comment] 2021-10-03 14:38
Are you really passing nothing as the value of `--overrideargs`? Why?

**Comment by jberezanski** [comment] 2021-10-03 14:39
In any case, this seems to be a problem with choco.exe, not with this package.

**Comment by jberezanski** [comment] 2021-10-03 14:45
From the log:
```
2021-09-30 10:49:28,190 19020 [ERROR] - ERROR: The string is missing the terminator: '.
2021-09-30 10:49:28,194 19020 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\netfx-4.7.2-devpack\tools\ChocolateyInstall.ps1' -installArguments '' -packageParameters '\"'--quiet' -overrideArgs'] exited with '-1'.
```

The packageParameters value passed by choco.exe to the chocolateyScriptRunner.ps1 script seems to be quoted incorrectly, causing the error.

**Comment by jberezanski** [comment] 2021-10-03 14:49
Also, the `--overrideargs` switch would effectively prevent the package logic from working correctly, even if choco did not cause the earlier error.

**Comment by BlythMeister** [comment] 2021-10-03 15:00
I was trying to make it forget the remembered args, put the wrong console output.  But happened regardless.

As soon as I made it not include remembered args, the package upgrade was fine.
I guess something has gone wrong in the saving of remembered args....those args also seem to be from the package that depends on this, rather than this package.

Because removing the args solved the issue, I think your right...it's not this package.

**Comment by jberezanski** [comment] 2021-10-03 19:19
Did you, by any chance, use the ["apply parameters to dependencies"](https://docs.chocolatey.org/en-us/choco/commands/install#options-and-switches) option when installing Visual Studio? That might explain the problem.

```
     --argsglobal, --args-global, --installargsglobal, --install-args-global, --applyargstodependencies, --apply-args-to-dependencies, --apply-install-arguments-to-dependencies
     Apply Install Arguments To Dependencies  - Should install arguments be 
       applied to dependent packages? Defaults to false.

     --paramsglobal, --params-global, --packageparametersglobal, --package-parameters-global, --applyparamstodependencies, --apply-params-to-dependencies, --apply-package-parameters-to-dependencies
     Apply Package Parameters To Dependencies  - Should package parameters be 
       applied to dependent packages? Defaults to false.
```

(both of those options are "broken by design" and should never be used, except for some very specific circumstances)

**Comment by BlythMeister** [comment] 2021-10-03 19:32
Not to my knowledge.  Unless my machine settings are wrong...

**Comment by jberezanski** [comment] 2021-10-03 19:49
I don't know of any other intentional mechanism in Choco that could cause such "leakage" of package parameters. Another bug, perhaps.

But that's actually irrelevant here. The `netfx-4.7.2-devpack` package does not accept any package parameters (it ignores them completely). So even if the Visual Studio package parameters (or even a random string of characters) were passed to `netfx-4.7.2-devpack`, it would not influence the installation in any way. The root problem is, however, that choco.exe mishandles the parameters - it quotes them incorrectly, resulting in a PowerShell syntax error. It might be worth reporting as an issue to [chocolatey/choco](https://github.com/chocolatey/choco/issues).

**Comment by jberezanski** [comment] 2021-12-29 21:13
Closing, as it is most likely a bug in Chocolatey.

**Closed by jberezanski** 2021-12-29 21:13 UTC
