### ISSUE TITLE
Windows Update extension requires active WUSA and installs ALL pending updates

### ISSUE THREAD

**Issue by riezebosch** [jberezanski/ChocolateyPackages#4] opened 2017-03-09 07:54 UTC
I use chocolatey/boxstarter to provision machines in a training environment. All computers are freshly installed multiple times a week. Therefor I only install the absolute minimum. But by using your VisualStudio2017Enterprise package I also need to install the required updates. That is in itself not a problem. But your chocolatey-windowsupdate.extension requires the WUSA to be running and by itself it starts to install all pending updates that are not strictly required to get Visual Studio up and running. That's a real problem to me.

![usd9dw](https://cloud.githubusercontent.com/assets/1427334/23750968/9cbb126a-04cf-11e7-90d5-223f88482564.jpg)

On further inspection it doesn't look like your package fault but Boxstarter sees WUSA in a running state and decides somehow to install all missing updates. Nonetheless it are still your packages that require the WUSA to be running. Am I correct?

Oh, and your package fails because it is not running inside a PowerShell 5 host.

**Comment by jberezanski** [comment] 2017-03-10 10:39
Yes, installing Windows updates requires the Windows Update service to be running.

By itself this should not be a problem (at least on Windows 8.1/2012 R2 or earlier), because Windows Update can be configured to never install updates automatically. I have several test machines I test my packages on and I've never seen a case where installing an update via wusa.exe caused other updates to be automatically installed. So, it does seem to be a Boxstarter issue.

(One terminology nitpick: WUSA = wusa.exe = Windows Update Standalone Installer, the command-line tool used to initiate manual update installation. The service responsible for performing the actual installation of updates and hosting the Automatic Updates functionality is simply called "Windows Update" (wuauserv). The entire subsystem is called the Windows Update Agent.)

If you would like to ensure that your machines have automatic update installation disabled, you can use the following snippet:

	$objAutoUpdate = New-Object -ComObject Microsoft.Update.AutoUpdate
	$objAutoUpdateSettings = $objAutoUpdate.Settings
	$objAutoUpdateSettings.NotificationLevel = 1 # aunlDisabled https://msdn.microsoft.com/en-us/library/windows/desktop/aa385806(v=vs.85).aspx
	$objAutoUpdateSettings.Save()

(this does not work on Windows 10/Server 2016, where Windows Update always acts as if value 4 = aunlScheduledInstallation = "Install updates automatically" was specified, but AFAIK there are no KB packages for those systems on chocolatey.org - not yet, at least)

About PowerShell 5: please post a log of such a failure - the packages are specifically designed to work on PowerShell 2.0 and later, in fact, I routinely install them on several systems: a vanilla Windows 7 with no updates and PowerShell 2; Windows 8.1 with PS 4; Windows 10 1511 with PS 5; Windows 10 1607 with PS 5.1.

**Comment by jberezanski** [comment] 2017-06-05 21:54
Closing as By Design (requires the Windows Update service to be running) and Invalid/External (the extension, by itself, does not install all pending updates).

**Closed by jberezanski** 2017-06-05 21:54 UTC

**Comment by jberezanski** [comment] 2017-12-11 18:13
It seems it got confirmed to be an issue with Boxstarter, which overwrites a function used in the KB packages with its own one, which does exactly what you describe: mwrock/boxstarter#293

**Comment by riezebosch** [comment] 2017-12-13 13:24
Thanks for the heads up!
