### ISSUE TITLE
The install of visualstudio2017-workload-netweb was NOT successful (in Docker)

### ISSUE THREAD

**Issue by goffinf** [jberezanski/ChocolateyPackages#31] opened 2017-12-07 21:24 UTC
The following error is emitting when attempting to install this package on Windows Server 2016. Any chance you can take a look please :-

choco install visualstudio2017-workload-netweb --confirm --limit-output --timeout 21600 --package-parameters "--includeOptional"

ERROR: Exception calling "GetFullPath" with "1" argument(s): "The path is not of a legal form."
The install of visualstudio2017-workload-netweb was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2017-workload-netweb\tools\ChocolateyInstall.ps1'.

**Comment by jberezanski** [comment] 2017-12-07 21:28
I would like to see your chocolatey.log (C:\ProgramData\Chocolatey\Logs\chocolatey.log). You can, for example, upload it as a [gist](https://gist.github.com).

**Comment by goffinf** [comment] 2017-12-07 21:43
Ok, I ran it inside a Docker container which I have since destroyed, but I’ll do it again tomorrow and post back here. I raised the same issue for workload-netcoretools and the same again for workload-azure (I haven’t raised that one yet but it’s likely to be the same issue

**Comment by jberezanski** [comment] 2017-12-08 17:39
It's probably a duplicate of #28, but I'd still like to look at your log - there might be something unique there because of Docker.

**Comment by goffinf** [comment] 2017-12-08 23:31
chocolatey.log attached.

I don't think it shows anything unusual that is specific to docker. I ran a cut down image build to include install of chocolatey itself, git, visualstudio2017enterprise and then visualstudio2017-workload-netweb, which is where we see the error. Below is the Dockerfile I used so you can see whats going on.

As others have commented this looks like a common error condition across this and other 'workload' installs. The log also shows the problem with uninstall that others have mentioned too : 

Regards

Fraser.

```
FROM microsoft/vsts-agent:windows-10.0.14393

ENV chocolateyUseWindowsCompression=false
RUN @powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

RUN choco config set cachelocation C:\chococache

RUN choco install \
    git  \
    --confirm \
    --limit-output \
    --timeout 216000 \
    && rmdir /S /Q C:\chococache

RUN choco install \
    dotnet4.6.1 \
    --confirm \
    --limit-output \
    && rmdir /S /Q C:\chococache

RUN choco install \
    visualstudio2017enterprise \
    --package-parameters "--passive --locale en-US --includeOptional" \
    --confirm \
    --limit-output \
    --timeout 216000 \
    && rmdir /S /Q C:\chococache
    
RUN choco install \
    visualstudio2017-workload-netweb \
    --confirm \
    --limit-output \
    --timeout 21600 \
    --package-parameters "--includeOptional" \
    && rmdir /S /Q C:\chococache
```

[chocolatey.log](https://github.com/jberezanski/ChocolateyPackages/files/1544093/chocolatey.log)

**Comment by jberezanski** [comment] 2017-12-09 00:51
Thank you! Yes, the log shows nothing unusual.
I'm releasing the fixed packages right now.

**Comment by jawn** [comment] 2018-11-13 10:12
This can be closed?

**Comment by jberezanski** [comment] 2018-11-15 20:05
I guess so.

**Closed by jberezanski** 2018-11-15 20:05 UTC
