### ISSUE TITLE
vcredist-all install fails because vcredist2010 is currently broken

### ISSUE THREAD

**Issue by mloskot** [jberezanski/ChocolateyPackages#102] opened 2021-04-21 16:19 UTC
I'm installing the `vcredist-all` for the first time on Docker container based on `mcr.microsoft.com/windows/servercore:20H2` and it looks like the `vcredist2010` is not available.

The fairly recent comment at http://disq.us/p/2gc4t0i by @jberezanski seems to confirm the 2010 one should be pulled by the package:
>  Installing the vcredist-all package on a clean system has the effect of installing the newest versions of all distinct Visual C++ runtimes since 2005.

I tried the `choco install -y vcredist-all` twice, every time in fresh container.
Here is complete `choco` output:

```
> choco install -y vcredist-all
Chocolatey v0.10.15
Installing the following packages:
vcredist-all
By installing you accept licenses for the packages.
Progress: Downloading vcredist2005 8.1.0.20160118... 100%
Progress: Downloading vcredist-all 1.0.0... 100%
Progress: Downloading vcredist2008 9.0.30729.6163... 100%
Progress: Downloading vcredist2010 10.0.40219.2... 100%
Progress: Downloading vcredist2012 11.0.61031... 100%
Progress: Downloading vcredist2013 12.0.40660.20180427... 100%
Progress: Downloading vcredist140 14.28.29914... 100%
Progress: Downloading chocolatey-core.extension 1.3.5.1... 100%
Progress: Downloading KB3033929 1.0.5... 100%
Progress: Downloading chocolatey-windowsupdate.extension 1.0.4... 100%
Progress: Downloading KB3035131 1.0.3... 100%
Progress: Downloading KB2919355 1.0.20160915... 100%
Progress: Downloading KB2919442 1.0.20160915... 100%
Progress: Downloading KB2999226 1.0.20181019... 100%
Progress: Downloading vcredist2015 14.0.24215.20170201... 100%
Progress: Downloading vcredist2017 14.16.27033... 100%

vcredist2005 v8.1.0.20160118 [Approved]
vcredist2005 package files install completed. Performing other installation steps.
WARNING: Url has SSL/TLS available, switching to HTTPS for download
Downloading vcredist2005 64 bit
  from 'https://download.microsoft.com/download/8/B/4/8B42259F-5D70-43F4-AC2E-4B208FD8D66A/vcredist_x64.EXE'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist2005\8.1.0.20160118\vcredist_x64.EXE (3.03 MB).
Download of vcredist_x64.EXE (3.03 MB) completed.
Hashes match.
Installing vcredist2005...
vcredist2005 has been installed.
WARNING: Url has SSL/TLS available, switching to HTTPS for download
Downloading vcredist2005
  from 'https://download.microsoft.com/download/8/B/4/8B42259F-5D70-43F4-AC2E-4B208FD8D66A/vcredist_x86.EXE'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist2005\8.1.0.20160118\vcredist_x86.EXE (2.58 MB).
Download of vcredist_x86.EXE (2.58 MB) completed.
Hashes match.
Installing vcredist2005...
vcredist2005 has been installed.
  vcredist2005 may be able to be automatically uninstalled.
 The install of vcredist2005 was successful.
  Software installed as 'exe', install location is likely default.

vcredist2008 v9.0.30729.6163 [Approved]
vcredist2008 package files install completed. Performing other installation steps.
Downloading vcredist2008 64 bit
  from 'https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x64.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist2008\9.0.30729.6163\vcredist_x64.exe (4.97 MB).
Download of vcredist_x64.exe (4.97 MB) completed.
Hashes match.
Installing vcredist2008...
vcredist2008 has been installed.
Downloading vcredist2008 32 bit
  from 'https://download.microsoft.com/download/5/D/8/5D8C65CB-C849-4025-8E95-C3966CAFD8AE/vcredist_x86.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist2008\9.0.30729.6163\vcredist_x86.exe (4.27 MB).
Download of vcredist_x86.exe (4.27 MB) completed.
Hashes match.
Installing vcredist2008...
vcredist2008 has been installed.
  vcredist2008 may be able to be automatically uninstalled.
 The install of vcredist2008 was successful.
  Software installed as 'exe', install location is likely default.

vcredist2010 v10.0.40219.2 [Approved]
vcredist2010 package files install completed. Performing other installation steps.
Attempt to get headers for http://download.microsoft.com/download/C/6/D/C6D0FD4E-9E53-4897-9B91-836EBA2AACD3/vcredist_x86.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://download.microsoft.com/download/C/6/D/C6D0FD4E-9E53-4897-9B91-836EBA2AACD3/vcredist_x86.exe'. Exception calling "GetResponse" with "0" argument(s):
 "The remote server returned an error: (404) Not Found."
Downloading vcredist2010
  from 'http://download.microsoft.com/download/C/6/D/C6D0FD4E-9E53-4897-9B91-836EBA2AACD3/vcredist_x86.exe'
WARNING: Write-ChocolateyFailure is deprecated and will be removed in v2. If you are the package maintainer, please use 'throw $_.Exception' instead.
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'http://download.microsoft.com/download/C/6/D/C6D0FD4E-9E53-4897-9B91-836EBA2AACD3/vcredist_x86.exe'. Exception calling "GetResponse" with "0" argumen
t(s): "The remote server returned an error: (404) Not Found."
The install of vcredist2010 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\vcredist2010\tools\chocolateyInstall.ps1'.
 See log for details.

vcredist2012 v11.0.61031 [Approved]
vcredist2012 package files install completed. Performing other installation steps.
WARNING: Url has SSL/TLS available, switching to HTTPS for download
Downloading vcredist2012 64 bit
  from 'https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist2012\11.0.61031\vcredist_x64.exe (6.85 MB).
Download of vcredist_x64.exe (6.85 MB) completed.
Hashes match.
Installing vcredist2012...
vcredist2012 has been installed.
WARNING: Url has SSL/TLS available, switching to HTTPS for download
Downloading vcredist2012
  from 'https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist2012\11.0.61031\vcredist_x86.exe (6.25 MB).
Download of vcredist_x86.exe (6.25 MB) completed.
Hashes match.
Installing vcredist2012...
vcredist2012 has been installed.
  vcredist2012 may be able to be automatically uninstalled.
 The install of vcredist2012 was successful.
  Software installed as 'EXE', install location is likely default.

vcredist2013 v12.0.40660.20180427 [Approved]
vcredist2013 package files install completed. Performing other installation steps.
Downloading vcredist2013 64 bit
  from 'https://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x64.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist2013\12.0.40660.20180427\vcredist_x64.exe (6.87 MB).
Download of vcredist_x64.exe (6.87 MB) completed.
Hashes match.
Installing vcredist2013...
vcredist2013 has been installed.
Downloading vcredist2013
  from 'https://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x86.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist2013\12.0.40660.20180427\vcredist_x86.exe (6.21 MB).
Download of vcredist_x86.exe (6.21 MB) completed.
Hashes match.
Installing vcredist2013...
vcredist2013 has been installed.
  vcredist2013 may be able to be automatically uninstalled.
 The install of vcredist2013 was successful.
  Software installed as 'exe', install location is likely default.

chocolatey-core.extension v1.3.5.1 [Approved]
chocolatey-core.extension package files install completed. Performing other installation steps.
 Installed/updated chocolatey-core extensions.
 The install of chocolatey-core.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-core'

chocolatey-windowsupdate.extension v1.0.4 [Approved]
chocolatey-windowsupdate.extension package files install completed. Performing other installation steps.
 Installed/updated chocolatey-windowsupdate extensions.
 The install of chocolatey-windowsupdate.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-windowsupdate'

KB3035131 v1.0.3 [Approved]
kb3035131 package files install completed. Performing other installation steps.
Skipping installation because update KB3035131 does not apply to this operating system (Microsoft Windows Server Datacenter).
 The install of kb3035131 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB3033929 v1.0.5 [Approved]
kb3033929 package files install completed. Performing other installation steps.
Skipping installation because update KB3033929 does not apply to this operating system (Microsoft Windows Server Datacenter).
 The install of kb3033929 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB2919442 v1.0.20160915 [Approved]
kb2919442 package files install completed. Performing other installation steps.
Skipping installation because this hotfix only applies to Windows 8.1 and Windows Server 2012 R2.
 The install of kb2919442 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB2919355 v1.0.20160915 [Approved]
kb2919355 package files install completed. Performing other installation steps.
Skipping installation because this hotfix only applies to Windows 8.1 and Windows Server 2012 R2.
 The install of kb2919355 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB2999226 v1.0.20181019 [Approved] - Possibly broken
kb2999226 package files install completed. Performing other installation steps.
Skipping installation because update KB2999226 does not apply to this operating system (Microsoft Windows Server Datacenter).
 The install of kb2999226 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

vcredist140 v14.28.29914 [Approved]
vcredist140 package files install completed. Performing other installation steps.
Downloading vcredist140-x86
  from 'https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/14563755AC24A874241935EF2C22C5FCE973ACB001F99E524145113B2DC638C1/VC_redist.x86.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist140\14.28.29914\VC_redist.x86.exe (13.66 MB).
Download of VC_redist.x86.exe (13.66 MB) completed.
Hashes match.
Installing vcredist140-x86...
vcredist140-x86 has been installed.
Downloading vcredist140-x64 64 bit
  from 'https://download.visualstudio.microsoft.com/download/pr/85d47aa9-69ae-4162-8300-e6b7e4bf3cf3/52B196BBE9016488C735E7B41805B651261FFA5D7AA86EB6A1D0095BE83687B2/VC_redist.x64.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist140\14.28.29914\VC_redist.x64.exe (14.19 MB).
Download of VC_redist.x64.exe (14.19 MB) completed.
Hashes match.
Installing vcredist140-x64...
vcredist140-x64 has been installed.
  vcredist140 may be able to be automatically uninstalled.
 The install of vcredist140 was successful.
  Software installed as 'exe', install location is likely default.

vcredist2015 v14.0.24215.20170201 [Approved]
vcredist2015 package files install completed. Performing other installation steps.
 The install of vcredist2015 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

vcredist2017 v14.16.27033 [Approved]
vcredist2017 package files install completed. Performing other installation steps.
 The install of vcredist2017 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

vcredist-all v1.0.0 [Approved] - Possibly broken
vcredist-all package files install completed. Performing other installation steps.
 The install of vcredist-all was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 15/16 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Installed:
 - kb2919355 v1.0.20160915
 - vcredist2012 v11.0.61031
 - kb3033929 v1.0.5
 - chocolatey-core.extension v1.3.5.1
 - kb2999226 v1.0.20181019
 - vcredist2005 v8.1.0.20160118
 - vcredist2015 v14.0.24215.20170201
 - vcredist2008 v9.0.30729.6163
 - kb2919442 v1.0.20160915
 - vcredist-all v1.0.0
 - vcredist2017 v14.16.27033
 - vcredist140 v14.28.29914
 - vcredist2013 v12.0.40660.20180427
 - kb3035131 v1.0.3
 - chocolatey-windowsupdate.extension v1.0.4

Failures
 - vcredist2010 (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\vcredist2010\tools\chocolateyInstall.ps1'.
 See log for details.
```

-----

UPDATE: Although the old URLs to VC++ Redist 2010 no longer work, the x84 and x64 packages can be downloaded from https://www.microsoft.com/en-US/Download/confirmation.aspx?id=26999

and direct download URLs figured, e.g. 
```
curl https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe --output vcredist2010_x64.exe
```

**Comment by jberezanski** [comment] 2021-04-22 23:33
Yes, I've reported this to the maintainer of the `vcredist2010` package, offering to take over maintenance of that package (in order to update the url), but no response yet.

I'll give the maintainer a few more days to respond and then escalate to the chocolatey.org admins.

**Comment by jberezanski** [comment] 2021-04-22 23:37
The cause is that the vcredist2010 package was using outdated urls, leading to older versions of the VC++ 2010 runtime. Microsoft has apparently removed those older versions from the Download Center, breaking the package. The fix is to update the package to use those urls you quoted.

Meanwhile, to avoid the `vcredist-all` package failing, you can cheat a little:
```
cinst -y vcredist2010 --skip-powershell    # this will cause Chocolatey to skip the install script, so the package will not fail
cinst -y vcredist-all
# then proceed to download and install the 2010 redist manually, if needed
```

**Comment by jberezanski** [comment] 2021-05-03 12:52
vcredist2010 is fixed now.

**Closed by jberezanski** 2021-05-03 12:52 UTC

**Comment by mloskot** [comment] 2021-05-04 09:51
Thank you
